### PR TITLE
Fix create balance when incomplete data

### LINKED ISSUE #314: `/teiserver/admin/matches/:match_id` fails, while `/battle/:match_id/ratings` works, after #235
@jauggy, do you think I could ask you to adjust the `admin/matches/:match_id` page just like you did for `battle/:match_id`? I'm guessing `admin/match_controller.ex` needs to get updated arguments but I'm out of mana to fix it at the moment :(

Here's an example of a match it fails on:
 
image

<details>
<summary>Phoenix logs, these should be enough</summary>

# KeyError at GET /teiserver/admin/matches/2783079

Exception:

    ** (KeyError) key :rating not found in: 31.785895067571246. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (teiserver 0.1.0) lib/teiserver/battle/libs/balance_lib.ex:109: anonymous fn/1 in Teiserver.Battle.BalanceLib.create_balance/3
        (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (teiserver 0.1.0) lib/teiserver/battle/libs/balance_lib.ex:109: anonymous fn/1 in Teiserver.Battle.BalanceLib.create_balance/3
        (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (teiserver 0.1.0) lib/teiserver/battle/libs/balance_lib.ex:107: Teiserver.Battle.BalanceLib.create_balance/3
        (teiserver 0.1.0) lib/teiserver_web/controllers/admin/match_controller.ex:134: TeiserverWeb.Admin.MatchController.show/2
        (teiserver 0.1.0) lib/teiserver_web/controllers/admin/match_controller.ex:1: TeiserverWeb.Admin.MatchController.action/2
        (teiserver 0.1.0) lib/teiserver_web/controllers/admin/match_controller.ex:1: TeiserverWeb.Admin.MatchController.phoenix_controller_pipeline/2
        (phoenix 1.7.6) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (teiserver 0.1.0) lib/teiserver_web/endpoint.ex:1: TeiserverWeb.Endpoint.plug_builder_call/2
        (teiserver 0.1.0) lib/plug/debugger.ex:136: TeiserverWeb.Endpoint."call (overridable 3)"/2
        (teiserver 0.1.0) lib/teiserver_web/endpoint.ex:1: TeiserverWeb.Endpoint.call/2
        (phoenix 1.7.6) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    

Code:

`lib/teiserver/battle/libs/balance_lib.ex`

    104       # an ID that's used purely for this run of balance
    105       expanded_groups =
    106         groups
    107         |&gt; Enum.map(fn members -&gt;
    108           userids = Map.keys(members)
    109&gt;          ratings = Map.values(members) |&gt; Enum.map(fn x -&gt; x.rating end)
    110   
    111           ranks =
    112             Map.values(members)
    113             |&gt; Enum.map(fn x -&gt;
    114               cond do
    
`lib/enum.ex`

    No code available.

`lib/teiserver/battle/libs/balance_lib.ex`

    104       # an ID that's used purely for this run of balance
    105       expanded_groups =
    106         groups
    107         |&gt; Enum.map(fn members -&gt;
    108           userids = Map.keys(members)
    109&gt;          ratings = Map.values(members) |&gt; Enum.map(fn x -&gt; x.rating end)
    110   
    111           ranks =
    112             Map.values(members)
    113             |&gt; Enum.map(fn x -&gt;
    114               cond do
    
`lib/enum.ex`

    No code available.

`lib/teiserver/battle/libs/balance_lib.ex`

    102   
    103       # We perform all our group calculations here and assign each group
    104       # an ID that's used purely for this run of balance
    105       expanded_groups =
    106         groups
    107&gt;        |&gt; Enum.map(fn members -&gt;
    108           userids = Map.keys(members)
    109           ratings = Map.values(members) |&gt; Enum.map(fn x -&gt; x.rating end)
    110   
    111           ranks =
    112             Map.values(members)
    
`lib/teiserver_web/controllers/admin/match_controller.ex`

    129             end)
    130         end)
    131         |&gt; List.flatten()
    132   
    133       past_balance =
    134&gt;        BalanceLib.create_balance(groups, match.team_count, mode: :loser_picks)
    135         |&gt; Map.put(:balance_mode, :grouped)
    136   
    137       # What about new balance?
    138       new_balance = generate_new_balance_data(match)
    139   
    
`lib/teiserver_web/controllers/admin/match_controller.ex`

    1&gt;  defmodule TeiserverWeb.Admin.MatchController do
    2     use TeiserverWeb, :controller
    3   
    4     alias Teiserver.{Battle, Game, Account, Telemetry}
    5     alias Teiserver.Battle.{MatchLib, BalanceLib}
    6     import Teiserver.Helper.StringHelper, only: [get_hash_id: 1]
    
`lib/teiserver_web/controllers/admin/match_controller.ex`

    1&gt;  defmodule TeiserverWeb.Admin.MatchController do
    2     use TeiserverWeb, :controller
    3   
    4     alias Teiserver.{Battle, Game, Account, Telemetry}
    5     alias Teiserver.Battle.{MatchLib, BalanceLib}
    6     import Teiserver.Helper.StringHelper, only: [get_hash_id: 1]
    
`lib/phoenix/router.ex`

    425           :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    426           halted_conn
    427   
    428         %Plug.Conn{} = piped_conn -&gt;
    429           try do
    430&gt;            plug.call(piped_conn, plug.init(opts))
    431           else
    432             conn -&gt;
    433               measurements = %{duration: System.monotonic_time() - start}
    434               metadata = %{metadata | conn: conn}
    435               :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    
`lib/teiserver_web/endpoint.ex`

    1&gt;  defmodule TeiserverWeb.Endpoint do
    2     use Phoenix.Endpoint, otp_app: :teiserver
    3   
    4     @session_options [
    5       store: :cookie,
    6       key: "_teiserver_key",
    
`lib/plug/debugger.ex`

    No code available.

`lib/teiserver_web/endpoint.ex`

    1&gt;  defmodule TeiserverWeb.Endpoint do
    2     use Phoenix.Endpoint, otp_app: :teiserver
    3   
    4     @session_options [
    5       store: :cookie,
    6       key: "_teiserver_key",
    
`lib/phoenix/endpoint/sync_code_reload_plug.ex`

    17   
    18     def call(conn, {endpoint, opts}), do: do_call(conn, endpoint, opts, true)
    19   
    20     defp do_call(conn, endpoint, opts, retry?) do
    21       try do
    22&gt;        endpoint.call(conn, opts)
    23       rescue
    24         exception in [UndefinedFunctionError] -&gt;
    25           case exception do
    26             %UndefinedFunctionError{module: ^endpoint} when retry? -&gt;
    27               # Sync with the code reloader and retry once
    
`lib/plug/cowboy/handler.ex`

    6     def init(req, {plug, opts}) do
    7       conn = @connection.conn(req)
    8   
    9       try do
    10         conn
    11&gt;        |&gt; plug.call(opts)
    12         |&gt; maybe_send(plug)
    13         |&gt; case do
    14           %Plug.Conn{adapter: {@connection, %{upgrade: {:websocket, websocket_args}} = req}} = conn -&gt;
    15             {handler, state, cowboy_opts} = websocket_args
    16             {__MODULE__, copy_resp_headers(conn, req), {handler, state}, cowboy_opts}
    
`deps/cowboy/src/cowboy_handler.erl`

    32   -optional_callbacks([terminate/3]).
    33   
    34   -spec execute(Req, Env) -&gt; {ok, Req, Env}
    35   	when Req::cowboy_req:req(), Env::cowboy_middleware:env().
    36   execute(Req, Env=#{handler := Handler, handler_opts := HandlerOpts}) -&gt;
    37&gt;  	try Handler:init(Req, HandlerOpts) of
    38   		{ok, Req2, State} -&gt;
    39   			Result = terminate(normal, Req2, State, Handler),
    40   			{ok, Req2, Env#{result =&gt; Result}};
    41   		{Mod, Req2, State} -&gt;
    42   			Mod:upgrade(Req2, Env, Handler, State);
    
`deps/cowboy/src/cowboy_stream_h.erl`

    301   	end.
    302   
    303   execute(_, _, []) -&gt;
    304   	ok;
    305   execute(Req, Env, [Middleware|Tail]) -&gt;
    306&gt;  	case Middleware:execute(Req, Env) of
    307   		{ok, Req2, Env2} -&gt;
    308   			execute(Req2, Env2, Tail);
    309   		{suspend, Module, Function, Args} -&gt;
    310   			proc_lib:hibernate(?MODULE, resume, [Env, Tail, Module, Function, Args]);
    311   		{stop, _Req2} -&gt;
    
`deps/cowboy/src/cowboy_stream_h.erl`

    290   %% to simplify the debugging of errors. The proc_lib library
    291   %% already adds the stacktrace to other types of exceptions.
    292   -spec request_process(cowboy_req:req(), cowboy_middleware:env(), [module()]) -&gt; ok.
    293   request_process(Req, Env, Middlewares) -&gt;
    294   	try
    295&gt;  		execute(Req, Env, Middlewares)
    296   	catch
    297   		exit:Reason={shutdown, _}:Stacktrace -&gt;
    298   			erlang:raise(exit, Reason, Stacktrace);
    299   		exit:Reason:Stacktrace when Reason =/= normal, Reason =/= shutdown -&gt;
    300   			erlang:raise(exit, {Reason, Stacktrace}, Stacktrace)
    
`proc_lib.erl`

    No code available.

### Params

    %{"id" =&gt; "2783079"}

### Request info

  * URI: .../teiserver/admin/matches/2783079
  * Query string: 

</details>

### PR DESCRIPTION
**Pull request by jauggy**
Fixes #314 

## Unit Test Steps
```
mix test --only balance_test
```

## Test Steps
Run local browser. Login as admin. Go to Admin > Matches > Show a match > Go to balance tab
It should have no errors

### CODE REVIEW

File: test/teiserver/battle/split_one_chevs_internal_test.exs [hunk 1]
```diff
@@ -4,30 +4,50 @@ defmodule Teiserver.Battle.SplitOneChevsInternalTest do
   Can run tests in this file only by
   mix test test/teiserver/battle/split_one_chevs_internal_test.exs
   """
-  use Teiserver.DataCase, async: true
+  use ExUnit.Case
   @moduletag :balance_test
```
Comment (jauggy) [inline test/teiserver/battle/split_one_chevs_internal_test.exs:8]: Changes to this file are just formatting and also since we don't hit the db, we use ExUnit instead

File: lib/teiserver/battle/libs/balance_lib.ex [hunk 2]
```diff
@@ -154,6 +155,30 @@ defmodule Teiserver.Battle.BalanceLib do
...
+              is_number(value) -> get_user_rating_rank_old(user_id, value)
+              true -> value
+            end
+
+          {nil, Map.put(acc, user_id, fixed_value)}
+        end)
+
+      better_map
+    end)
+  end
```
Comment (geekingfrog) [inline lib/teiserver/battle/libs/balance_lib.ex:180]: If I understand this bit correctly, when the value in the map is not a user struct, you want to fetch the corresponding user and replace the id with that user right?

In that case there's a much simpler way: `Enum.map`

```elixir
    Enum.map(groups, fn group ->
      group
      |> Enum.map(fn {user_id, value} ->
        cond do
          is_number(value) -> {user_id, get_user_rating_rank_old(user_id, value)}
          true -> {user_id, value}
        end
      end)
      |> Enum.into(%{})
    end)
```

or, if you prefer using guards, you can also do the following

```elixir
    Enum.map(groups, fn group ->
      group
      |> Enum.map(fn
        {user_id, value} when is_number(value) ->
          {user_id, get_user_rating_rank_old(user_id, value)}

        {user_id, value} ->
          {user_id, value}
      end)
      |> Enum.into(%{})
    end)
```

The advantage of `Enum.map` is that the intent is clearer, you are applying some sort of transformation on every element. In the case of a map it's a tuple of `{key, value}`.
When using `map_reduce`, it's a lot more complicated to figure out what's going on. The fact that you had to discard one of the return value is a code smell as well.

File: test/teiserver/battle/balance_lib_internal_test.exs [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+    :ok
+  end
+
+  test "Able to standardise groups with incomplete data" do
+    groups = [
+      %{1 => 19, 2 => 20},
+      %{3 => 18},
+      %{4 => 15},
+      %{5 => 11}
+    ]
```
Comment (geekingfrog) [inline test/teiserver/battle/balance_lib_internal_test.exs:24]: I am not a fan at all of the use of mocks. It forces you to have a deep knowledge of the internals of the stuff you're testing. You recognise that with the comment a bit bellow:
> loser_picks algo will hit the databases so let's just test with split_one_chevs

It's also a departure from the other tests elsewhere.

For these reason, I'd rather have something that creates the mock data in the DB, and then exercise the code under test.

Using `DataCase, async: true`, I propose the following:
```elixir
    [user1, user2, user3, user4, user5] =
      Enum.map(1..5, fn k ->
        Teiserver.TeiserverTestLib.new_user("User_#{k}")
      end)

    groups = [
      %{user1.id => 19, user2.id => 20},
      %{user3.id => 18},
      %{user4.id => 15},
      %{user5.id => 11}
    ]

    fixed_groups = BalanceLib.standardise_groups(groups)

    assert fixed_groups == [
             %{
               user1.id => %{name: "User_1", rank: 0, rating: 19},
               user2.id => %{name: "User_2", rank: 0, rating: 20}
             },
             %{user3.id => %{name: "User_3", rank: 0, rating: 18}},
             %{user4.id => %{name: "User_4", rank: 0, rating: 15}},
             %{user5.id => %{name: "User_5", rank: 0, rating: 11}}
           ]
```

and similar for the other test. You could even consider pulling the creation of users in a setup function for the module.

Let me know if you have any question over this code.

File: test/teiserver/battle/balance_lib_internal_test.exs [hunk 4]
```diff
@@ -0,0 +1,59 @@
+defmodule Teiserver.Battle.BalanceLibInternalTest do
+  @moduledoc """
+  Can run all balance tests via
+  mix test --only balance_test
+  """
+  use ExUnit.Case
+  import Mock
+  @moduletag :balance_test
```
Comment (geekingfrog) [inline test/teiserver/battle/balance_lib_internal_test.exs:8]: I'm not convinced by this tag. Test tags should be used for logical grouping only. Like `tag: cluster` when you have several tests spanning multiple files testing one feature.
If you only want to test one file, you can always run `mix test path/to/the/file`

**Review by geekingfrog — COMMENTED** [review]
Nice fix, left a few comments about general code quality, but the functionality looks good.

File: test/teiserver/battle/balance_lib_internal_test.exs (hunk 4 above)
Comment (jauggy) [reply test/teiserver/battle/balance_lib_internal_test.exs:8]: The other balance tests are tagged already though. So it's hitting multiple files.

File: lib/teiserver/battle/libs/balance_lib.ex (hunk 2 above)
Comment (jauggy) [reply lib/teiserver/battle/libs/balance_lib.ex:180]: I had a feeling there was a better way to do it. Before you reviewed this, I had already posted a question on Elixir forums: https://elixirforum.com/t/iterate-through-map-of-dynamic-keys-and-update-their-values/64061/3
I'm liking the idea of Map.new

File: test/teiserver/battle/balance_lib_internal_test.exs (hunk 3 above)
Comment (jauggy) [reply test/teiserver/battle/balance_lib_internal_test.exs:24]: After creating these users, do they get deleted at some point at end of test?

**Comment by jauggy** [comment]
@geekingfrog have updated the unit test to use the db instead of mocks. But if I try and run it multiple times it will fail. try
```
mix test path/to/balance_lib_internal_test.exs
```
Try running this multiple times and it should fail. I'm not sure how to fix.

**Comment by StanczakDominik** [comment]
I've applied the mix format stuff from master :)

File: mix.lock [hunk 5]
```diff
@@ -59,10 +59,12 @@
...
   "merkle_map": {:hex, :merkle_map, "0.2.1", "01a88c87a6b9fb594c67c17ebaf047ee55ffa34e74297aa583ed87148006c4c8", [:mix], [], "hexpm", "fed4d143a5c8166eee4fa2b49564f3c4eace9cb252f0a82c1613bba905b2d04d"},
   "metrics": {:hex, :metrics, "1.0.1", "25f094dea2cda98213cecc3aeff09e940299d950904393b2a29d191c346a8486", [:rebar3], [], "hexpm", "69b09adddc4f74a40716ae54d140f93beb0fb8978d8636eaded0c31b6f099f16"},
   "mime": {:hex, :mime, "1.6.0", "dabde576a497cef4bbdd60aceee8160e02a6c89250d6c0b29e56c0dfb00db3d2", [:mix], [], "hexpm", "31a1a8613f8321143dde1dafc36006a17d28d02bdfecb9e95a880fa7aabd19a7"},
   "mimerl": {:hex, :mimerl, "1.2.0", "67e2d3f571088d5cfd3e550c383094b47159f3eee8ffa08e64106cdf5e981be3", [:rebar3], [], "hexpm", "f278585650aa581986264638ebf698f8bb19df297f66ad91b18910dfc6e19323"},
+  "mock": {:hex, :mock, "0.3.8", "7046a306b71db2488ef54395eeb74df0a7f335a7caca4a3d3875d1fc81c884dd", [:mix], [{:meck, "~> 0.9.2", [hex: :meck, repo: "hexpm", optional: false]}], "hexpm", "7fa82364c97617d79bb7d15571193fc0c4fe5afd0c932cef09426b3ee6fe2022"},
```
Comment (StanczakDominik) [inline mix.lock:67]: Didn't we end up going without mocking? Tap apply if true :)
```suggestion
  "merkle_map": {:hex, :merkle_map, "0.2.1", "01a88c87a6b9fb594c67c17ebaf047ee55ffa34e74297aa583ed87148006c4c8", [:mix], [], "hexpm", "fed4d143a5c8166eee4fa2b49564f3c4eace9cb252f0a82c1613bba905b2d04d"},
  "metrics": {:hex, :metrics, "1.0.1", "25f094dea2cda98213cecc3aeff09e940299d950904393b2a29d191c346a8486", [:rebar3], [], "hexpm", "69b09adddc4f74a40716ae54d140f93beb0fb8978d8636eaded0c31b6f099f16"},
  "mime": {:hex, :mime, "1.6.0", "dabde576a497cef4bbdd60aceee8160e02a6c89250d6c0b29e56c0dfb00db3d2", [:mix], [], "hexpm", "31a1a8613f8321143dde1dafc36006a17d28d02bdfecb9e95a880fa7aabd19a7"},
  "mimerl": {:hex, :mimerl, "1.2.0", "67e2d3f571088d5cfd3e550c383094b47159f3eee8ffa08e64106cdf5e981be3", [:rebar3], [], "hexpm", "f278585650aa581986264638ebf698f8bb19df297f66ad91b18910dfc6e19323"},
```

**Review by StanczakDominik — APPROVED** [review]
Looks good and I tested it on the lobbies that previously failed; the test failure on multiple runs is another issue, so I think it's fine to ignore until we fix it at the root cause. As long as the tests pass "once" (which is why having CI that we can take as mostly-a-source-of-truth is helpful) after dropping the database, I'm fine with this.

Thank you! :)

**Comment by jauggy** [comment]
Have added https://github.com/beyond-all-reason/teiserver/issues/317
so that someone can fix the tests not clearing. I couldn't figure it out.
